repos:
  - repo: local
    hooks:
      - id: astro-check
        name: astro check
        entry: npm run check
        language: system
        pass_filenames: false
        types_or: [ts, astro, mdx, markdown]
